name: FastTravel
version: 1.0.0
main: me.harriiison.fasttravel.FastTravel
author: Harrison
description: An interactive fast travel plugin allowing players to interacts with transports and travel across the world.
depend: [Citizens]

commands:
  fasttravel:
    usage: /fasttravel reload
    description: Reload the Fast Travel config

permissions:
  fasttravel.admin:
    description: Use this plugin to access locations
    default: op